###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: docker-symfony4-mysql
      working_dir: /application
      volumes:
        - ./mysqldb:/application
      environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=dispatcher
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpw
      ports:
        - "3308:3306"

    webserver:
      image: nginx:alpine
      container_name: docker-symfony4-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    couchdb:
      image: couchdb:latest
      ports:
        - "5984:5984"
      environment:
               DB_USER: admin
               DB_PASSWORD: password
               DB_NAME: db_new

    php-fpm:
      build: phpdocker/php-fpm
      container_name: docker-symfony4-php-fpm
      working_dir: /application
      links:
          - couchdb
      volumes:
        - ./src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

